export const PLANETS = [
  {
    Name: 'Abyz',
    Comment: null,
    Tile: 'AbyzFria',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 3,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Arinam',
    Comment: null,
    Tile: 'ArinamMeer',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Arnor',
    Comment: null,
    Tile: 'ArnorLor',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 2,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Bereg',
    Comment: null,
    Tile: 'BeregLirta',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Centauri',
    Comment: null,
    Tile: 'CentauriGral',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 1,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Coorneeq',
    Comment: null,
    Tile: 'CoorneeqResculon',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Dal Bootha',
    Comment: null,
    Tile: 'DalBoothaXXehan',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 0,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Fria',
    Comment: null,
    Tile: 'AbyzFria',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 2,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Gral',
    Comment: null,
    Tile: 'CentauriGral',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 1,
    Tech: 'Blue',
  },
  {
    Name: 'Lazar',
    Comment: null,
    Tile: 'LazarSakulag',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 0,
    Tech: 'Yellow',
  },
  {
    Name: 'Lirta IV',
    Comment: null,
    Tile: 'BeregLirta',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 2,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Lodor',
    Comment: '⍺-Wormhole',
    Tile: '',
    Planet: 1,
    Trait: 'Cultural',
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Lor',
    Comment: null,
    Tile: 'ArnorLor',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Meer',
    Comment: null,
    Tile: 'ArinamMeer',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 0,
    Influence: 4,
    Tech: 'Red',
  },
  {
    Name: 'Mehar Xull',
    Comment: null,
    Tile: 'Mehar Xull',
    Planet: 1,
    Trait: 'Hazardous',
    Resource: 1,
    Influence: 3,
    Tech: 'Red',
  },
  {
    Name: 'Mellon',
    Comment: null,
    Tile: 'MellonZohbat',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 0,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'New Albion',
    Comment: null,
    Tile: 'NewAlbionStarpoint',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 1,
    Tech: 'Green',
  },
  {
    Name: 'Quann',
    Comment: 'β-Wormhole',
    Tile: '',
    Planet: 1,
    Trait: 'Cultural',
    Resource: 2,
    Influence: 1,
    Tech: null,
  },
  {
    Name: "Qucen'n",
    Comment: null,
    Tile: 'QuecenNRarron',
    Planet: 2,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Rarron',
    Comment: null,
    Tile: 'QuecenNRarron',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 0,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Resculon',
    Comment: null,
    Tile: 'CoorneeqResculon',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 2,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Sakulag',
    Comment: null,
    Tile: 'LazarSakulag',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 2,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Saudor',
    Comment: null,
    Tile: '',
    Planet: 1,
    Trait: 'Industrial',
    Resource: 2,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Starpoint',
    Comment: null,
    Tile: 'NewAlbionStarpoint',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: "Tar'Mann",
    Comment: null,
    Tile: '',
    Planet: 1,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 1,
    Tech: 'Green',
  },
  {
    Name: "Tequ'ran",
    Comment: null,
    Tile: "TorkanTequ'Ran",
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 2,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Thibah',
    Comment: null,
    Tile: '',
    Planet: 1,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 1,
    Tech: 'Blue',
  },
  {
    Name: 'Torkan',
    Comment: null,
    Tile: "TorkanTequ'Ran",
    Planet: 2,
    Trait: 'Cultural',
    Resource: 0,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Vefut II',
    Comment: null,
    Tile: '',
    Planet: 1,
    Trait: 'Hazardous',
    Resource: 2,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Wellon',
    Comment: null,
    Tile: '',
    Planet: 1,
    Trait: 'Industrial',
    Resource: 1,
    Influence: 2,
    Tech: 'Yellow',
  },
  {
    Name: 'XXehan',
    Comment: null,
    Tile: 'DalBoothaXXehan',
    Planet: 2,
    Trait: 'Cultural',
    Resource: 1,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Zohbat',
    Comment: null,
    Tile: 'MellonZohbat',
    Planet: 2,
    Trait: 'Hazardous',
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'NestPhar',
    Comment: 'Homeplanet',
    Tile: 'Arborec',
    Planet: 1,
    Trait: null,
    Resource: 3,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Creuss',
    Comment: 'Homeplanet, δ-Wormhole, Off-Map',
    Tile: 'Creuss',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Hercant',
    Comment: 'Homeplanet',
    Tile: 'Hacan',
    Planet: 3,
    Trait: null,
    Resource: 1,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Arretze',
    Comment: 'Homeplanet',
    Tile: 'Hacan',
    Planet: 3,
    Trait: null,
    Resource: 2,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Kamdorn',
    Comment: 'Homeplanet',
    Tile: 'Hacan',
    Planet: 3,
    Trait: null,
    Resource: 0,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Jol',
    Comment: 'Homeplanet',
    Tile: 'Jol-Nar',
    Planet: 2,
    Trait: null,
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Nar',
    Comment: 'Homeplanet',
    Tile: 'Jol-Nar',
    Planet: 2,
    Trait: null,
    Resource: 2,
    Influence: 3,
    Tech: null,
  },
  {
    Name: '[0.0.0]',
    Comment: 'Homeplanet',
    Tile: 'L1Z1x',
    Planet: 1,
    Trait: null,
    Resource: 5,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Arc Prime',
    Comment: 'Homeplanet',
    Tile: 'Letnev',
    Planet: 2,
    Trait: null,
    Resource: 4,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Wren Terra',
    Comment: 'Homeplanet',
    Tile: 'Letnev',
    Planet: 2,
    Trait: null,
    Resource: 2,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Moll Primus',
    Comment: 'Homeplanet',
    Tile: 'Mentak',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Muuat',
    Comment: 'Homeplanet',
    Tile: 'Muaat',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Druaa',
    Comment: 'Homeplanet',
    Tile: 'Naalu',
    Planet: 2,
    Trait: null,
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Maaluuk',
    Comment: 'Homeplanet',
    Tile: 'Naalu',
    Planet: 2,
    Trait: null,
    Resource: 0,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Mordai II',
    Comment: 'Homeplanet',
    Tile: 'Nekro Virus',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Lisis II',
    Comment: 'Homeplanet',
    Tile: 'Saar',
    Planet: 2,
    Trait: null,
    Resource: 1,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Ragh',
    Comment: 'Homeplanet',
    Tile: 'Saar',
    Planet: 2,
    Trait: null,
    Resource: 2,
    Influence: 1,
    Tech: null,
  },
  {
    Name: "Tren'Lak",
    Comment: 'Homeplanet',
    Tile: "Sardakk N'orr",
    Planet: 2,
    Trait: null,
    Resource: 1,
    Influence: 0,
    Tech: null,
  },
  {
    Name: 'Quinarra',
    Comment: 'Homeplanet',
    Tile: "Sardakk N'orr",
    Planet: 2,
    Trait: null,
    Resource: 3,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Jord',
    Comment: 'Homeplanet',
    Tile: 'Sol',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Winnu',
    Comment: 'Homeplanet',
    Tile: 'Winnu',
    Planet: 1,
    Trait: null,
    Resource: 3,
    Influence: 4,
    Tech: null,
  },
  {
    Name: 'Archon Wren',
    Comment: 'Homeplanet',
    Tile: 'Xxcha',
    Planet: 2,
    Trait: null,
    Resource: 2,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Archon Tau',
    Comment: 'Homeplanet',
    Tile: 'Xxcha',
    Planet: 2,
    Trait: null,
    Resource: 1,
    Influence: 1,
    Tech: null,
  },
  {
    Name: 'Darien',
    Comment: 'Homeplanet',
    Tile: 'Yin',
    Planet: 1,
    Trait: null,
    Resource: 4,
    Influence: 4,
    Tech: null,
  },
  {
    Name: 'Retillion',
    Comment: 'Homeplanet',
    Tile: 'Yssaril',
    Planet: 2,
    Trait: null,
    Resource: 2,
    Influence: 3,
    Tech: null,
  },
  {
    Name: 'Shalloq',
    Comment: 'Homeplanet',
    Tile: 'Yssaril',
    Planet: 2,
    Trait: null,
    Resource: 1,
    Influence: 2,
    Tech: null,
  },
  {
    Name: 'Mecatol Rex',
    Comment: null,
    Tile: 'Mecatol Rex',
    Planet: 1,
    Trait: null,
    Resource: 1,
    Influence: 6,
    Tech: null,
  },
];
